# WireGuard tunnel to the home FRITZ!Box.
#
# Purpose: machines on the home LAN reach this server *transparently* — no
# client software, no VPN app, no route to configure. That works because
# FRITZ!OS does not route a transfer network into the LAN; it proxy-ARPs the
# peer's tunnel address onto the LAN segment. So this host takes an address
# out of 10.2.0.0/24 and, to a LAN client, is indistinguishable from a machine
# plugged into the switch. Real client source addresses, no NAT.
#
# DIRECTION: this host DIALS OUT. The FRITZ!Box is the WireGuard server and has
# no endpoint configured for us. That is not what was originally planned — the
# server has the static address, so it looked like the natural listener — but
# AVM's "Netzwerke koppeln" wizard offers no field for a peer endpoint at all.
# It works out fine: this box is the always-on, network-stable side, which makes
# it the better dialer anyway, and PersistentKeepalive holds the path open.
#
# The FRITZ!Box side is NOT managed here. It lives in the router's own config
# (Internet -> Freigaben -> VPN (WireGuard), connection "ionos-vps" — the
# router's own label, predating this host's rename to p-ion-berlin-xs56r6) and is the
# one part of this host that no amount of `nixos-rebuild` can reconstruct. Its
# peer entry routes exactly 10.2.0.203/32 and fd11:1b58:53c0::203/128 to us.
{ ... }:
let
  # Public key material — safe in a public repo, same class as authorized_keys.
  fritzBoxPublicKey = "5XR4vHwk3zcZvpPFudHG6M25uXxgX+vV0WsTYXEYzxI=";

  # The FRITZ!Box's dynamic-DNS name and the port AVM picked. Deliberately in
  # the clear despite this repo being public: it is a name anyone can already
  # resolve, and hiding it would mean a PostUp that reads it from sops at
  # runtime, because wg-quick bakes the endpoint in at build time.
  fritzBoxEndpoint = "hallstein.ignorelist.com:58419";

  homeLan4 = "10.2.0.0/24";
  homeLan6 = "fd11:1b58:53c0::/64";

  # Assigned by the FRITZ!Box, not chosen here — its peer entry is pinned to
  # these. Note .203 sits outside the router's DHCP pool (10.2.0.20-200).
  selfAddr4 = "10.2.0.203";
  selfAddr6 = "fd11:1b58:53c0::203";
in
{
  # `{ config, ... }` on the INNER function, not the outer one. The outer
  # `config` is flake-parts' own; reaching for `config.sops` there fails with a
  # bare "attribute 'sops' missing" that says nothing about the real cause.
  flake.modules.nixos.wireguard-home = { config, ... }: {
    # networking.wg-quick, NOT networking.wireguard. The latter's `useNetworkd`
    # defaults to `cfg.interfaces != {}` (a 2019 backwards-compatibility
    # default), so merely defining an interface selects the networkd backend —
    # which attaches the key to systemd-networkd.service via LoadCredential. A
    # missing key file would then take down the ENTIRE network stack on the next
    # restart, on a host whose only fallback is a KVM console. wg-quick fails as
    # one oneshot unit instead.
    networking.wg-quick.interfaces.wg0 = {
      # /32 and /128, where the FRITZ!Box's generated config said /24 and /64.
      # Same result, less collision: a /24 here would add a connected route for
      # 10.2.0.0/24 AND wg-quick would add the same route from allowedIPs. The
      # prefix length is local-only — the router never sees it.
      address = [ "${selfAddr4}/32" "${selfAddr6}/128" ];

      # Pinned rather than ephemeral, and that is load-bearing: this host dials
      # out, so its source port is what return traffic comes back to. The IONOS
      # provider firewall (no API, configured by hand, recorded in
      # infra/src/inventory.ts) has an inbound UDP/51820 rule, which therefore
      # covers the replies even if that firewall turns out to filter statelessly.
      listenPort = 51820;

      # AVM's WireGuard uses 1280 and does not negotiate. Leave this at the
      # 1420 default and the tunnel pings fine, then stalls on the first
      # full-size TCP segment — a genuinely nasty thing to debug later.
      mtu = 1280;

      # From sops, not generatePrivateKeyFile. The key was generated by the
      # FRITZ!Box when the connection was created there, and the router's peer
      # entry is pinned to the matching public half — so a key regenerated on
      # first boot would leave the tunnel dead until someone edits the router by
      # hand. This way a reinstall restores a working tunnel.
      privateKeyFile = config.sops.secrets.wireguard_wg0_private.path;

      # A LIST, because a second site (the NAS at its own location) is expected
      # to join later as another peer rather than as a redesign.
      peers = [
        {
          publicKey = fritzBoxPublicKey;
          endpoint = fritzBoxEndpoint;

          # The FRITZ!Box generated a preshared key, so this side MUST have it
          # too — a PSK is symmetric and mixed into the handshake, so a
          # one-sided one means no connection at all. The failure mode is a
          # tunnel that never completes a handshake, which looks exactly like a
          # blocked UDP port; easy to spend an afternoon on the wrong layer.
          #
          # Never appears in the generated .conf, which lives world-readable in
          # /nix/store. wg-quick applies it from a PostUp hook instead:
          #   wg set wg0 peer <pubkey> preshared-key <(cat <file>)
          # (That process substitution is safe here: the hook is built with
          # pkgs.writeShellScriptBin, which is bash, not dash.)
          presharedKeyFile = config.sops.secrets.wireguard_wg0_preshared.path;

          # NARROWED on purpose. AVM's generated config offers
          # `0.0.0.0/0, ::/0` — its wizard's "standalone connection" answer
          # means full tunnel — which would push this server's entire internet
          # traffic through a domestic uplink. allowedIPs is our side's choice,
          # so the router needs no change for this.
          allowedIPs = [ homeLan4 homeLan6 ];

          # The dialling side owns keepalive; without it the router's NAT state
          # expires and the tunnel goes quiet until this host sends something.
          persistentKeepalive = 25;
        }
      ];
    };

    # Tier 2 of three (tier 1 = public internet, tier 3 = tailnet, see
    # modules/nixos-tailscale.nix). Deliberately an explicit allow-list and NOT
    # `trustedInterfaces = [ "wg0" ]`: because the FRITZ!Box does not NAT, the
    # source addresses arriving here are EVERY device on the home LAN — guests,
    # IoT, whatever is plugged in. Blanket trust would hand all of them every
    # future service that happens to bind 0.0.0.0.
    #
    # SSH is reachable over wg0 regardless, and that is wanted: NixOS' top-level
    # `allowedTCPPorts` is the global tier (rules with no `-i`), so port 22
    # matches on every interface. That makes 10.2.0.203 a second, real-sshd
    # deploy path if the public one is ever lost.
    networking.firewall.interfaces.wg0.allowedTCPPorts = [ ];

    # No inbound UDP hole is opened here. The host firewall is stateful
    # (nixos-fw starts with a conntrack RELATED,ESTABLISHED accept), and this
    # side initiates, so replies are already allowed. The IONOS rule mentioned
    # above exists for the provider layer, where statefulness is not documented.
  };
}
