# sops-nix on the NixOS class.
#
# The first non-workstation secret store in this repo. modules/secrets.nix is
# home-manager only and stays that way: it decrypts into a user's home with a
# user's SSH identity, which is the wrong shape for a headless server whose
# secrets are consumed by system services before anyone logs in.
#
# Deliberately NOT a shared mkSecretsModule with modules/secrets.nix. The two
# have almost nothing in common beyond the word "sops": different module class,
# different identity, different consumers, and no shared secret. Factoring them
# together would create a coupling that only makes both harder to read.
{ inputs, lib, ... }:
let
  root = ./..;

  mkSecretsModule = hostId: { ... }:
    let
      hostSecretsFile = root + "/hosts/${hostId}/secrets.enc.yaml";
      hostSecretsModule = root + "/hosts/${hostId}/secrets.nix";

      # Same contract as the workstations: hosts/<host>/secrets.nix lists
      # exactly the keys present in that host's encrypted YAML.
      hostSecrets =
        if builtins.pathExists hostSecretsModule then import hostSecretsModule else { };
    in
    {
      imports = [ inputs.sops-nix.nixosModules.sops ];

      sops = {
        # A DEDICATED key, generated on the host itself, not
        # /etc/ssh/ssh_host_ed25519_key (which is sops-nix's default). The host
        # key is regenerated by a reinstall, and since a reinstall is this
        # machine's documented recovery procedure, using it would mean every
        # secret silently becomes unreadable at exactly the moment things are
        # already going badly.
        #
        # Created once, by hand, and its private half has never left the box:
        #   install -d -m0700 /var/lib/sops-nix
        #   ssh-keygen -t ed25519 -N "" -C "sops@<host>" \
        #     -f /var/lib/sops-nix/ssh_ed25519_sops
        #   chmod 0400 /var/lib/sops-nix/ssh_ed25519_sops
        # The public half is a recipient in .sops.yaml; see the comment there
        # for why losing this key costs a re-encrypt and nothing more.
        age.sshKeyPaths = [ "/var/lib/sops-nix/ssh_ed25519_sops" ];

        # No defaultSopsFile: unlike the workstations there is no global file
        # this host may read. Every secret is host-scoped and names its file, so
        # an accidental reference to a workstation secret fails to evaluate
        # instead of failing to decrypt at boot.
        secrets = lib.mapAttrs
          (_: secret: { sopsFile = hostSecretsFile; } // secret)
          hostSecrets;
      };
    };
in
{
  flake.modules.nixos.secrets-p-ion-berlin-xs56r6 = mkSecretsModule "p-ion-berlin-xs56r6";
}
