{
  # Host-specific secrets for ionos-vps (NixOS).
  #
  # Each attribute here is merged into sops.secrets by
  # modules/nixos-secrets.nix and gets
  # sopsFile = hosts/ionos-vps/secrets.enc.yaml. Unlike the workstations
  # there is no global file this host may read: every secret is host-scoped.
  #
  # These are SYSTEM secrets, decrypted to /run/secrets/<name> before the
  # services that need them start — not into anyone's home directory.

  # WireGuard private key for wg0 (modules/nixos-wireguard-home.nix).
  #
  # Generated by the FRITZ!Box when the "ionos-vps" connection was created
  # there; the plaintext lives in 1Password. It is a secret and not a
  # generated-on-first-boot key on purpose: the FRITZ!Box's peer entry is
  # pinned to the matching PUBLIC key, so a key regenerated by a reinstall
  # would leave the tunnel dead until someone edits the router by hand.
  #
  # mode 0400 / owner root: wg-quick reads it as root at interface setup.
  wireguard_wg0_private = {
    mode = "0400";
    owner = "root";
  };

  # WireGuard preshared key for the same peer. NOT optional here, even though
  # WireGuard treats PSKs as optional in general: the FRITZ!Box put one in the
  # connection it generated, and a PSK is symmetric. If one side has it and the
  # other does not, the handshake simply never completes — and the symptom is
  # indistinguishable from a blocked port, which would send anyone debugging it
  # off to look at firewalls.
  #
  # wg-quick never writes this into the interface's .conf (that file lands
  # world-readable in /nix/store). It is applied by a PostUp hook instead:
  #   wg set wg0 peer <pubkey> preshared-key <(cat /run/secrets/...)
  wireguard_wg0_preshared = {
    mode = "0400";
    owner = "root";
  };
}
